import type {
  Entity,
  ActivityItem,
  CaseFile,
  Alert,
  Transaction,
  GraphNode,
  GraphEdge,
  Hotspot,
  FinancialFlowNode,
  FinancialFlowLink,
} from '@/types';

export const entities: Entity[] = [
  {
    id: 'P001',
    name: 'Ramesh Kumar',
    type: 'person',
    status: 'criminal',
    aliases: ['Ramesh Yadav', 'RK', 'Bhai'],
    dob: '1985-03-15',
    aadhaar: 'XXXX-XXXX-4523',
    phone: '+91 98765 43210',
    address: 'Sector 14, Gurugram, Haryana',
    criminalRecord: '7 prior FIRs — Extortion (2), Arms Act (3), Fraud (2). Active warrant since 2024.',
    threatLevel: 'critical',
    confidenceScore: 94,
  },
  {
    id: 'P002',
    name: 'Imran Sheikh',
    type: 'person',
    status: 'criminal',
    aliases: ['Imran Bhai'],
    dob: '1990-07-22',
    aadhaar: 'XXXX-XXXX-8891',
    phone: '+91 90043 11245',
    address: 'Old City, Hyderabad, Telangana',
    criminalRecord: '4 prior FIRs — Smuggling (2), Narcotics (2). Suspected cross-border links.',
    threatLevel: 'critical',
    confidenceScore: 89,
    aiInferred: true,
  },
  {
    id: 'P003',
    name: 'Sunita Devi',
    type: 'person',
    status: 'poi',
    aliases: ['Sunita Sharma'],
    dob: '1992-11-08',
    aadhaar: 'XXXX-XXXX-2271',
    phone: '+91 98220 67430',
    address: 'Kothrud, Pune, Maharashtra',
    criminalRecord: 'Suspected money mule. Under surveillance since Jan 2025.',
    threatLevel: 'high',
    confidenceScore: 72,
    aiInferred: true,
  },
  {
    id: 'P004',
    name: 'Vikram Singh',
    type: 'person',
    status: 'poi',
    aliases: ['Vikram Rathore'],
    dob: '1988-01-30',
    aadhaar: 'XXXX-XXXX-9945',
    phone: '+91 70123 88910',
    address: 'Vaishali Nagar, Jaipur, Rajasthan',
    criminalRecord: 'Person of Interest — frequent contact with known offenders.',
    threatLevel: 'high',
    confidenceScore: 68,
    aiInferred: true,
  },
  {
    id: 'P005',
    name: 'Anil Mehta',
    type: 'person',
    status: 'verified',
    aliases: [],
    dob: '1979-06-12',
    aadhaar: 'XXXX-XXXX-3382',
    phone: '+91 98100 22310',
    address: 'Lajpat Nagar, New Delhi',
    criminalRecord: 'No record. Verified identity — businessman.',
    threatLevel: 'info',
  },
  {
    id: 'P006',
    name: 'Deepak Tyagi',
    type: 'person',
    status: 'criminal',
    aliases: ['DT', 'Deepak Chacha'],
    dob: '1975-09-18',
    aadhaar: 'XXXX-XXXX-7710',
    phone: '+91 99100 44567',
    address: 'Indirapuram, Ghaziabad, UP',
    criminalRecord: '12 prior FIRs — Murder (1), Extortion (4), Land Grabbing (3), Arms (4). Kingpin suspect.',
    threatLevel: 'critical',
    confidenceScore: 97,
  },
  {
    id: 'P007',
    name: 'Fatima Khan',
    type: 'person',
    status: 'poi',
    aliases: ['Fatima Ali'],
    dob: '1995-04-03',
    aadhaar: 'XXXX-XXXX-5561',
    phone: '+91 89045 12390',
    address: 'Charminar, Hyderabad, Telangana',
    criminalRecord: 'Suspected courier. Multiple CDR anomalies detected.',
    threatLevel: 'warning',
    confidenceScore: 61,
    aiInferred: true,
  },
  {
    id: 'P008',
    name: 'Rajesh Verma',
    type: 'person',
    status: 'verified',
    aliases: [],
    dob: '1983-12-25',
    aadhaar: 'XXXX-XXXX-1190',
    phone: '+91 98230 78120',
    address: 'Andheri West, Mumbai, Maharashtra',
    criminalRecord: 'No record. Verified — bank employee.',
    threatLevel: 'info',
  },
  {
    id: 'PH001',
    name: '+91 98765 43210',
    type: 'phone',
    status: 'criminal',
    aliases: [],
    threatLevel: 'critical',
  },
  {
    id: 'PH002',
    name: '+91 90043 11245',
    type: 'phone',
    status: 'criminal',
    aliases: [],
    threatLevel: 'critical',
  },
  {
    id: 'PH003',
    name: '+91 98220 67430',
    type: 'phone',
    status: 'poi',
    aliases: [],
    threatLevel: 'high',
  },
  {
    id: 'PH004',
    name: '+91 70123 88910',
    type: 'phone',
    status: 'poi',
    aliases: [],
    threatLevel: 'high',
  },
  {
    id: 'AC001',
    name: 'HDFC ••4521',
    type: 'account',
    status: 'criminal',
    aliases: [],
    threatLevel: 'critical',
  },
  {
    id: 'AC002',
    name: 'SBI ••8890',
    type: 'account',
    status: 'poi',
    aliases: [],
    threatLevel: 'high',
  },
  {
    id: 'AC003',
    name: 'ICICI ••3382',
    type: 'account',
    status: 'verified',
    aliases: [],
    threatLevel: 'info',
  },
  {
    id: 'VH001',
    name: 'DL-3C-AX-9876',
    type: 'vehicle',
    status: 'criminal',
    aliases: [],
    threatLevel: 'critical',
  },
  {
    id: 'VH002',
    name: 'RJ-14-CD-4521',
    type: 'vehicle',
    status: 'poi',
    aliases: [],
    threatLevel: 'warning',
  },
  {
    id: 'L001',
    name: 'Gurugram Sector 14',
    type: 'location',
    status: 'asset',
    aliases: [],
    threatLevel: 'warning',
  },
  {
    id: 'L002',
    name: 'Old City, Hyderabad',
    type: 'location',
    status: 'asset',
    aliases: [],
    threatLevel: 'critical',
  },
  {
    id: 'L003',
    name: 'Ghaziabad Warehouse',
    type: 'location',
    status: 'asset',
    aliases: [],
    threatLevel: 'critical',
  },
];

export const graphNodes: GraphNode[] = [
  { id: 'P001', label: 'Ramesh Kumar', type: 'person', status: 'criminal', x: 400, y: 300, vx: 0, vy: 0, radius: 22, confidence: 94 },
  { id: 'P002', label: 'Imran Sheikh', type: 'person', status: 'criminal', x: 600, y: 200, vx: 0, vy: 0, radius: 20, confidence: 89 },
  { id: 'P003', label: 'Sunita Devi', type: 'person', status: 'poi', x: 250, y: 180, vx: 0, vy: 0, radius: 16, confidence: 72, aiInferred: true },
  { id: 'P004', label: 'Vikram Singh', type: 'person', status: 'poi', x: 550, y: 420, vx: 0, vy: 0, radius: 16, confidence: 68, aiInferred: true },
  { id: 'P005', label: 'Anil Mehta', type: 'person', status: 'verified', x: 150, y: 380, vx: 0, vy: 0, radius: 14 },
  { id: 'P006', label: 'Deepak Tyagi', type: 'person', status: 'criminal', x: 700, y: 350, vx: 0, vy: 0, radius: 24, confidence: 97 },
  { id: 'P007', label: 'Fatima Khan', type: 'person', status: 'poi', x: 480, y: 120, vx: 0, vy: 0, radius: 15, confidence: 61, aiInferred: true },
  { id: 'P008', label: 'Rajesh Verma', type: 'person', status: 'verified', x: 320, y: 480, vx: 0, vy: 0, radius: 13 },
  { id: 'PH001', label: '+91 98765 43210', type: 'phone', status: 'criminal', x: 340, y: 250, vx: 0, vy: 0, radius: 12 },
  { id: 'PH002', label: '+91 90043 11245', type: 'phone', status: 'criminal', x: 660, y: 150, vx: 0, vy: 0, radius: 12 },
  { id: 'PH003', label: '+91 98220 67430', type: 'phone', status: 'poi', x: 200, y: 250, vx: 0, vy: 0, radius: 10 },
  { id: 'PH004', label: '+91 70123 88910', type: 'phone', status: 'poi', x: 600, y: 480, vx: 0, vy: 0, radius: 10 },
  { id: 'AC001', label: 'HDFC ••4521', type: 'account', status: 'criminal', x: 450, y: 380, vx: 0, vy: 0, radius: 14 },
  { id: 'AC002', label: 'SBI ••8890', type: 'account', status: 'poi', x: 180, y: 150, vx: 0, vy: 0, radius: 12 },
  { id: 'AC003', label: 'ICICI ••3382', type: 'account', status: 'verified', x: 100, y: 320, vx: 0, vy: 0, radius: 10 },
  { id: 'VH001', label: 'DL-3C-AX-9876', type: 'vehicle', status: 'criminal', x: 520, y: 340, vx: 0, vy: 0, radius: 12 },
  { id: 'VH002', label: 'RJ-14-CD-4521', type: 'vehicle', status: 'poi', x: 650, y: 500, vx: 0, vy: 0, radius: 10 },
  { id: 'L001', label: 'Gurugram Sec 14', type: 'location', status: 'asset', x: 380, y: 200, vx: 0, vy: 0, radius: 13 },
  { id: 'L002', label: 'Old City, Hyd', type: 'location', status: 'asset', x: 580, y: 100, vx: 0, vy: 0, radius: 13 },
  { id: 'L003', label: 'Ghaziabad Wh.', type: 'location', status: 'asset', x: 750, y: 280, vx: 0, vy: 0, radius: 13 },
];

export const graphEdges: GraphEdge[] = [
  { id: 'E1', source: 'P001', target: 'PH001', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E2', source: 'P001', target: 'AC001', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E3', source: 'P001', target: 'VH001', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E4', source: 'P001', target: 'P006', label: 'Called 47x', type: 'call', inferred: false, weight: 3, metadata: { duration: '4h 23m total' } },
  { id: 'E5', source: 'P001', target: 'P003', label: 'Transferred ₹4.2L', type: 'money', inferred: false, weight: 2, metadata: { amount: '₹4,20,000' } },
  { id: 'E6', source: 'P001', target: 'L001', label: 'Visited 12x', type: 'visited', inferred: false, weight: 2 },
  { id: 'E7', source: 'P002', target: 'PH002', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E8', source: 'P002', target: 'P006', label: 'Associate', type: 'associate', inferred: true, weight: 2, confidence: 78 },
  { id: 'E9', source: 'P002', target: 'L002', label: 'Visited 8x', type: 'visited', inferred: false, weight: 2 },
  { id: 'E10', source: 'P002', target: 'P007', label: 'Called 23x', type: 'call', inferred: false, weight: 2, metadata: { duration: '2h 15m total' } },
  { id: 'E11', source: 'P003', target: 'PH003', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E12', source: 'P003', target: 'AC002', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E13', source: 'P003', target: 'P004', label: 'Associate', type: 'associate', inferred: true, weight: 1, confidence: 65 },
  { id: 'E14', source: 'P004', target: 'PH004', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E15', source: 'P004', target: 'VH002', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E16', source: 'P006', target: 'L003', label: 'Frequents', type: 'visited', inferred: false, weight: 3 },
  { id: 'E17', source: 'P006', target: 'AC001', label: 'Transferred ₹12L', type: 'money', inferred: false, weight: 3, metadata: { amount: '₹12,00,000' } },
  { id: 'E18', source: 'P005', target: 'AC003', label: 'Owns', type: 'owns', inferred: false, weight: 1 },
  { id: 'E19', source: 'P005', target: 'P001', label: 'Associate', type: 'associate', inferred: true, weight: 1, confidence: 54 },
  { id: 'E20', source: 'P007', target: 'P003', label: 'Associate', type: 'associate', inferred: true, weight: 1, confidence: 48 },
  { id: 'E21', source: 'P008', target: 'AC002', label: 'Access to', type: 'owns', inferred: false, weight: 1 },
  { id: 'E22', source: 'P006', target: 'P002', label: 'Transferred ₹8L', type: 'money', inferred: true, weight: 2, confidence: 82, metadata: { amount: '₹8,00,000' } },
  { id: 'E23', source: 'P004', target: 'P001', label: 'Called 15x', type: 'call', inferred: true, weight: 1, confidence: 71 },
];

export const activityFeed: ActivityItem[] = [
  { id: 'A1', timestamp: '2 min ago', description: 'Phone #98765 43210 pinged near Gurugram Sector 14 cell tower', source: 'CDR', threatLevel: 'critical', entityId: 'P001' },
  { id: 'A2', timestamp: '8 min ago', description: '₹4,20,000 transferred from HDFC ••4521 to SBI ••8890 — flagged: structuring pattern', source: 'Financial', threatLevel: 'critical', entityId: 'P001', aiInferred: true },
  { id: 'A3', timestamp: '15 min ago', description: 'Imran Sheikh detected in CCTV near Old City, Hyderabad', source: 'Surveillance', threatLevel: 'high', entityId: 'P002' },
  { id: 'A4', timestamp: '32 min ago', description: 'AI: New link detected between Vikram Singh and Ramesh Kumar (71% confidence)', source: 'AI', threatLevel: 'warning', entityId: 'P004', aiInferred: true },
  { id: 'A5', timestamp: '1 hr ago', description: 'FIR registered: Arms Act violation — Ghaziabad warehouse raid', source: 'FIR', threatLevel: 'critical', entityId: 'P006' },
  { id: 'A6', timestamp: '1 hr ago', description: 'Social media post flagged: Deepak Tyagi associate posted from Jaipur', source: 'Social Media', threatLevel: 'warning', entityId: 'P006' },
  { id: 'A7', timestamp: '2 hr ago', description: 'Vehicle DL-3C-AX-9876 ANPR match at Delhi-Gurgaon expressway', source: 'Surveillance', threatLevel: 'high', entityId: 'VH001' },
  { id: 'A8', timestamp: '3 hr ago', description: 'Fatima Khan contacted Sunita Devi — 3 calls totaling 47 minutes', source: 'CDR', threatLevel: 'warning', entityId: 'P007' },
  { id: 'A9', timestamp: '4 hr ago', description: 'AI: Financial anomaly — ₹8L routed through 3 shell accounts', source: 'AI', threatLevel: 'critical', aiInferred: true },
  { id: 'A10', timestamp: '5 hr ago', description: 'FIR updated: Case #FIR-2025-0421 — 2 new suspects added', source: 'FIR', threatLevel: 'info' },
];

export const alerts: Alert[] = [
  { id: 'AL1', title: 'Suspicious Financial Cluster', description: 'AI detected ₹18.5L flowing through 5 interconnected accounts with structuring patterns', severity: 'critical', timestamp: '2 min ago', source: 'AI Financial Analysis', status: 'new', entityId: 'P001', aiInferred: true },
  { id: 'AL2', title: 'Known Criminal Location Ping', description: 'Ramesh Kumar\'s phone detected near Gurugram Sector 14 — within 2km of prior incident site', severity: 'critical', timestamp: '8 min ago', source: 'CDR + Geospatial', status: 'new', entityId: 'P001' },
  { id: 'AL3', title: 'Cross-State Movement', description: 'Imran Sheikh surveillance match in Hyderabad — outside registered jurisdiction', severity: 'high', timestamp: '15 min ago', source: 'CCTV Surveillance', status: 'new', entityId: 'P002' },
  { id: 'AL4', title: 'New AI-Inferred Network Link', description: 'Vikram Singh linked to Ramesh Kumar network with 71% confidence via call pattern analysis', severity: 'warning', timestamp: '32 min ago', source: 'AI Link Inference', status: 'new', entityId: 'P004', aiInferred: true },
  { id: 'AL5', title: 'Vehicle ANPR Match', description: 'Vehicle DL-3C-AX-9876 (linked to Ramesh Kumar) detected on Delhi-Gurgaon expressway', severity: 'high', timestamp: '2 hr ago', source: 'ANPR System', status: 'investigating', entityId: 'VH001' },
  { id: 'AL6', title: 'Social Media Threat Post', description: 'Associate of Deepak Tyagi posted content flagged by NLP threat detection model', severity: 'warning', timestamp: '1 hr ago', source: 'Social Media Monitor', status: 'investigating', entityId: 'P006' },
];

export const cases: CaseFile[] = [
  { id: 'C1', firNumber: 'FIR-2025-0421', title: 'Ghaziabad Arms Smuggling Ring', status: 'under-investigation', priority: 'critical', assignedTo: 'ACP Sharma, R.', date: '2025-08-15', location: 'Ghaziabad, UP', suspects: 7, summary: 'Large-scale arms smuggling operation. Warehouse raided, 3 arrests, 4 absconding. Deepak Tyagi identified as kingpin.' },
  { id: 'C2', firNumber: 'FIR-2025-0388', title: 'Gurugram Extortion Network', status: 'open', priority: 'critical', assignedTo: 'SI Kapoor, M.', date: '2025-09-01', location: 'Gurugram, HR', suspects: 5, summary: 'Extortion ring targeting businessmen in Sector 14-18. Ramesh Kumar prime suspect. CDR and financial analysis ongoing.' },
  { id: 'C3', firNumber: 'FIR-2025-0356', title: 'Hyderabad Narcotics Channel', status: 'under-investigation', priority: 'high', assignedTo: 'DSP Reddy, K.', date: '2025-07-22', location: 'Hyderabad, TS', suspects: 4, summary: 'Cross-state narcotics distribution. Imran Sheikh and Fatima Khan identified as key couriers. Surveillance active.' },
  { id: 'C4', firNumber: 'FIR-2025-0299', title: 'Pune Money Laundering', status: 'open', priority: 'high', assignedTo: 'PI Deshmukh, S.', date: '2025-09-03', location: 'Pune, MH', suspects: 3, summary: 'Suspected money mule network using shell accounts. Sunita Devi under surveillance. ₹4.2L traced so far.' },
  { id: 'C5', firNumber: 'FIR-2024-1198', title: 'Jaipur Vehicle Theft Syndicate', status: 'cold', priority: 'warning', assignedTo: 'Unassigned', date: '2024-11-10', location: 'Jaipur, RJ', suspects: 2, summary: 'Vehicle theft ring. Vikram Singh person of interest. Case went cold — insufficient evidence. AI re-analysis requested.' },
  { id: 'C6', firNumber: 'FIR-2025-0501', title: 'Delhi Land Grabbing Case', status: 'closed', priority: 'warning', assignedTo: 'ACP Sharma, R.', date: '2025-06-18', location: 'New Delhi, DL', suspects: 1, summary: 'Land grabbing case linked to Deepak Tyagi network. Resolved — 1 conviction, property recovered.' },
];

export const transactions: Transaction[] = [
  { id: 'T1', from: 'AC001', to: 'AC002', fromLabel: 'HDFC ••4521 (Ramesh K.)', toLabel: 'SBI ••8890 (Sunita D.)', amount: 420000, date: '2025-09-04 14:32', flagged: true, aiInferred: true, confidence: 91 },
  { id: 'T2', from: 'AC001', to: 'AC003', fromLabel: 'HDFC ••4521 (Ramesh K.)', toLabel: 'ICICI ••3382 (Anil M.)', amount: 150000, date: '2025-09-04 12:15', flagged: false },
  { id: 'T3', from: 'AC002', to: 'AC001', fromLabel: 'SBI ••8890 (Sunita D.)', toLabel: 'HDFC ••4521 (Ramesh K.)', amount: 50000, date: '2025-09-04 11:00', flagged: true, aiInferred: true, confidence: 85 },
  { id: 'T4', from: 'AC001', to: 'AC002', fromLabel: 'HDFC ••4521 (Ramesh K.)', toLabel: 'SBI ••8890 (Sunita D.)', amount: 75000, date: '2025-09-03 22:45', flagged: true },
  { id: 'T5', from: 'AC001', to: 'AC003', fromLabel: 'HDFC ••4521 (Ramesh K.)', toLabel: 'ICICI ••3382 (Anil M.)', amount: 200000, date: '2025-09-03 18:20', flagged: false },
  { id: 'T6', from: 'AC002', to: 'AC001', fromLabel: 'SBI ••8890 (Sunita D.)', toLabel: 'HDFC ••4521 (Ramesh K.)', amount: 30000, date: '2025-09-03 09:00', flagged: true, aiInferred: true, confidence: 88 },
];

export const hotspots: Hotspot[] = [
  { id: 'H1', name: 'Gurugram, Haryana', x: 32, y: 38, intensity: 0.95, incidents: 47, type: 'Extortion' },
  { id: 'H2', name: 'Old City, Hyderabad', x: 52, y: 62, intensity: 0.88, incidents: 38, type: 'Narcotics' },
  { id: 'H3', name: 'Ghaziabad, UP', x: 40, y: 28, intensity: 0.92, incidents: 52, type: 'Arms Smuggling' },
  { id: 'H4', name: 'Pune, Maharashtra', x: 22, y: 55, intensity: 0.65, incidents: 19, type: 'Money Laundering' },
  { id: 'H5', name: 'Jaipur, Rajasthan', x: 30, y: 42, intensity: 0.72, incidents: 24, type: 'Vehicle Theft' },
  { id: 'H6', name: 'Mumbai, Maharashtra', x: 18, y: 58, intensity: 0.58, incidents: 31, type: 'Financial Fraud' },
  { id: 'H7', name: 'New Delhi', x: 38, y: 32, intensity: 0.81, incidents: 43, type: 'Mixed' },
  { id: 'H8', name: 'Bengaluru, Karnataka', x: 42, y: 72, intensity: 0.45, incidents: 12, type: 'Cybercrime' },
  { id: 'H9', name: 'Kolkata, WB', x: 68, y: 48, intensity: 0.62, incidents: 27, type: 'Human Trafficking' },
  { id: 'H10', name: 'Chennai, TN', x: 50, y: 78, intensity: 0.51, incidents: 16, type: 'Smuggling' },
];

export const financialFlowNodes: FinancialFlowNode[] = [
  { name: 'HDFC ••4521', color: '#FF0055' },
  { name: 'SBI ••8890', color: '#FFB300' },
  { name: 'ICICI ••3382', color: '#00E676' },
  { name: 'Shell Acct 1', color: '#FF0055' },
  { name: 'Shell Acct 2', color: '#FFB300' },
  { name: 'Cash Out', color: '#FF0055' },
];

export const financialFlowLinks: FinancialFlowLink[] = [
  { source: 0, target: 1, value: 420, flagged: true },
  { source: 0, target: 2, value: 150, flagged: false },
  { source: 0, target: 3, value: 200, flagged: true },
  { source: 1, target: 4, value: 80, flagged: true },
  { source: 3, target: 4, value: 180, flagged: true },
  { source: 4, target: 5, value: 260, flagged: true },
  { source: 1, target: 0, value: 50, flagged: true },
];

export const aiSuggestions = [
  { id: 'S1', title: 'Trace ₹4.2L transfer chain', description: 'Follow the money from HDFC ••4521 → SBI ••8890. AI detected a structuring pattern suggesting layering. Recommend freezing SBI account pending investigation.', confidence: 91 },
  { id: 'S2', title: 'Cross-reference Vikram Singh CDR', description: 'New AI-inferred link (71%) between Vikram Singh and Ramesh Kumar. Pull last 90 days of call records to confirm pattern.', confidence: 71 },
  { id: 'S3', title: 'Deploy surveillance to Old City, Hyderabad', description: 'Imran Sheikh detected outside registered jurisdiction. Recommend coordinating with Hyderabad Cybercrime unit.', confidence: 84 },
  { id: 'S4', title: 'Investigate Ghaziabad warehouse connections', description: 'Deepak Tyagi frequents L003 warehouse. AI identified 3 unregistered vehicles in ANPR data near this location.', confidence: 79 },
];

export function formatINR(amount: number): string {
  if (amount >= 10000000) return `₹${(amount / 10000000).toFixed(2)}Cr`;
  if (amount >= 100000) return `₹${(amount / 100000).toFixed(2)}L`;
  if (amount >= 1000) return `₹${(amount / 1000).toFixed(0)}K`;
  return `₹${amount}`;
}
